#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
UI Frontend Contract Checker

Validates that backend code properly integrates with UIProgressTracker to ensure the frontend
UI receives correct progress updates. Focuses on proper UIProgressTracker usage patterns rather
than low-level streaming details.

This checker ensures:
1. Backend code uses UIProgressTracker (not custom progress implementations)
2. UIProgressTracker is initialized with session_id for session isolation
3. Progress callbacks are properly configured
4. Tracker lifecycle methods (start/update/complete) are called correctly
5. Backend uses approved emoji indicators in log messages
6. No direct manipulation of SSE streams (use UIProgressTracker instead)

PRIMARY FOCUS: UIProgressTracker Integration
============================================
The frontend HTML (webapp/templates/index.html) listens for these events from UIProgressTracker:
- progress_update       : Generated by tracker.update() - includes percentage, current, total
- batch_summary         : Generated by BatchProgressTracker.complete_batch()
- phase_change          : Generated by tracker.set_phase()
- analysis_start        : Generated by tracker.start()
- analysis_completion   : Generated by tracker.complete()

CRITICAL: Backend code should use UIProgressTracker, NOT create custom SSE events!

UIProgressTracker Usage Pattern (from src/ui_progress_tracker.py):
===================================================================
✅ CORRECT:
    from src.ui_progress_tracker import UIProgressTracker
    
    tracker = UIProgressTracker(
        analysis_name="My Analysis",
        total_items=100,
        session_id=session_id,              # REQUIRED for session isolation
        progress_callback=my_callback,      # Callback function for updates
        phase_name="Initial Phase"
    )
    tracker.start()                         # Sends analysis_start event
    tracker.update(1)                       # Sends progress_update event
    tracker.complete(success=True)          # Sends analysis_completion event

❌ INCORRECT:
    # Don't create custom progress events
    callback({"type": "progress_update", "percentage": 50})  # WRONG!
    
    # Don't manipulate streaming directly
    yield format_sse(json.dumps(data), event="progress_update")  # WRONG!

REQUIRED TRACKER INITIALIZATION:
- session_id: MUST be provided for proper session isolation
- progress_callback: Function to send updates to frontend
- analysis_name: Name displayed in UI
- total_items: Total count for percentage calculation

APPROVED EMOJI INDICATORS (for logging only):
- 🚀 : Starting/Launch
- ✅ : Success/Completed
- ❌ : Error/Failed
- 📊 : Progress/Statistics
- 🔍 : Analysis/Inspection
- ⚠️ : Warning
- 📁 : File/Data
- 🎯 : Target/Goal
- 🔄 : Processing/Loop
- 💡 : Information/Tip

Usage:
    python uiFrontendContractChecker.py                    # Check all backend files
    python uiFrontendContractChecker.py --verbose          # Show detailed analysis
    python uiFrontendContractChecker.py --report           # Generate text report
    python uiFrontendContractChecker.py --output report.txt # Save report to file

Exit Codes:
    0 - No contract violations found
    1 - Critical contract violations detected (breaks UI)
"""

import os
import re
import sys
import ast
import argparse
from typing import List, Dict, Any, Set, Tuple, Optional
from dataclasses import dataclass, field
from pathlib import Path
from datetime import datetime


# ANSI color codes for terminal output
class Colors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'


@dataclass
class ContractViolation:
    """Represents a backend-frontend contract violation."""
    line_number: int
    violation_type: str
    severity: str  # 'critical', 'warning', 'info'
    message: str
    code_snippet: str
    fix_suggestion: str
    event_type: Optional[str] = None  # Which event type was violated


@dataclass
class FileValidationResult:
    """Results from validating a single file."""
    file_path: str
    violations: List[ContractViolation] = field(default_factory=list)
    approved_events: List[Dict[str, Any]] = field(default_factory=list)
    line_count: int = 0
    validation_score: float = 100.0


# UIProgressTracker integration patterns
REQUIRED_TRACKER_IMPORTS = [
    "from src.ui_progress_tracker import UIProgressTracker",
    "from src.ui_progress_tracker import create_analysis_tracker",
]

# UIProgressTracker lifecycle methods that should be called
TRACKER_LIFECYCLE_METHODS = {
    "start": "Initializes tracker and sends analysis_start event",
    "update": "Updates progress and sends progress_update event",
    "complete": "Finalizes tracker and sends analysis_completion event",
    "set_phase": "Changes analysis phase and sends phase_change event"
}

# Required parameters for UIProgressTracker initialization
REQUIRED_TRACKER_PARAMS = {
    "session_id": "Session identifier for isolation (CRITICAL)",
    "progress_callback": "Callback function to send updates to frontend",
    "analysis_name": "Name of the analysis displayed in UI",
    "total_items": "Total item count for percentage calculation"
}

# Anti-patterns that indicate incorrect usage
ANTI_PATTERNS = {
    "manual_event_creation": r'{\s*["\']type["\']\s*:\s*["\'](?:progress_update|batch_summary|analysis_start|analysis_completion)["\']',
    "direct_sse_streaming": r'format_sse\([^)]*event\s*=\s*["\'](?:progress_update|batch_summary|phase_change)',
    "custom_progress_dict": r'{\s*["\']percentage["\']\s*:.*["\']current["\']\s*:.*["\']total["\']',
}

APPROVED_EMOJIS = {
    "🚀": "Starting/Launch",
    "✅": "Success/Completed",
    "❌": "Error/Failed",
    "📊": "Progress/Statistics",
    "🔍": "Analysis/Inspection",
    "⚠️": "Warning",
    "📁": "File/Data",
    "🎯": "Target/Goal",
    "🔄": "Processing/Loop",
    "💡": "Information/Tip"
}


class FrontendContractChecker:
    """
    Validates that backend code adheres to the frontend SSE contract.
    Detects unauthorized event types, missing fields, and contract violations.
    """
    
    def __init__(self, base_path: str = None, verbose: bool = False):
        """
        Initialize the Frontend Contract Checker.
        
        Args:
            base_path: Base directory path (default: current directory)
            verbose: Enable verbose output
        """
        self.base_path = Path(base_path) if base_path else Path.cwd()
        self.verbose = verbose
        self.results: Dict[str, FileValidationResult] = {}
        self.backend_files = self._discover_backend_files()
        
        if self.verbose:
            print(f"{Colors.OKCYAN}🔍 Frontend Contract Checker initialized{Colors.ENDC}")
            print(f"{Colors.OKCYAN}📁 Base path: {self.base_path}{Colors.ENDC}")
            print(f"{Colors.OKCYAN}📄 Auto-discovered {len(self.backend_files)} Python files{Colors.ENDC}")
    
    def _discover_backend_files(self) -> List[str]:
        """
        Dynamically discover Python files that may send SSE events.
        Scans src/ and webapp/ directories for .py files.
        
        Returns:
            List of relative file paths to check
        """
        discovered_files = []
        
        # Search patterns for backend code
        search_dirs = ['src', 'webapp']
        
        for search_dir in search_dirs:
            dir_path = self.base_path / search_dir
            if not dir_path.exists():
                continue
            
            # Find all Python files recursively
            for py_file in dir_path.rglob('*.py'):
                # Skip __pycache__ and test files
                if '__pycache__' in str(py_file) or py_file.name.startswith('test_'):
                    continue
                
                # Get relative path from base
                rel_path = py_file.relative_to(self.base_path)
                discovered_files.append(str(rel_path).replace('\\', '/'))
        
        return sorted(discovered_files)
    
    def check_all_backend_files(self) -> Dict[str, FileValidationResult]:
        """
        Check all backend files for contract compliance.
        
        Returns:
            Dictionary mapping file paths to validation results
        """
        print(f"\n{Colors.HEADER}{'=' * 80}{Colors.ENDC}")
        print(f"{Colors.HEADER}{Colors.BOLD}🔍 FRONTEND CONTRACT VALIDATION{Colors.ENDC}")
        print(f"{Colors.HEADER}{'=' * 80}{Colors.ENDC}\n")
        
        print(f"{Colors.OKCYAN}📂 Scanning {len(self.backend_files)} Python files in src/ and webapp/{Colors.ENDC}\n")
        
        for file_rel_path in self.backend_files:
            file_path = self.base_path / file_rel_path
            
            if not file_path.exists():
                if self.verbose:
                    print(f"{Colors.WARNING}⚠️  File not found: {file_path}{Colors.ENDC}")
                continue
            
            print(f"{Colors.OKCYAN}📄 Checking: {file_rel_path}{Colors.ENDC}")
            result = self._validate_file(file_path)
            self.results[str(file_rel_path)] = result
            
            # Print detailed summary per file
            if result.violations:
                critical = [v for v in result.violations if v.severity == 'critical']
                warnings = [v for v in result.violations if v.severity == 'warning']
                
                if critical:
                    print(f"  {Colors.FAIL}❌ {len(critical)} critical violation(s):{Colors.ENDC}")
                    for v in critical[:3]:  # Show first 3 critical
                        print(f"     Line {v.line_number}: {v.message}")
                        
                if warnings:
                    print(f"  {Colors.WARNING}⚠️  {len(warnings)} warning(s):{Colors.ENDC}")
                    for v in warnings[:2]:  # Show first 2 warnings
                        print(f"     Line {v.line_number}: {v.message}")
            else:
                print(f"  {Colors.OKGREEN}✅ No contract violations{Colors.ENDC}")
        
        return self.results
    
    def _validate_file(self, file_path: Path) -> FileValidationResult:
        """
        Validate a single file for frontend contract compliance.
        
        Args:
            file_path: Path to file to validate
            
        Returns:
            FileValidationResult with violations found
        """
        result = FileValidationResult(file_path=str(file_path))
        
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
                lines = content.split('\n')
                result.line_count = len(lines)
            
            # PRIMARY CHECKS: UIProgressTracker usage
            self._check_tracker_import(content, lines, result)
            self._check_tracker_initialization(content, lines, result)
            self._check_session_id_usage(content, lines, result)
            self._check_anti_patterns(content, lines, result)
            
            # SECONDARY CHECKS: Code quality
            self._check_unauthorized_emojis(content, lines, result)
            self._check_tracker_lifecycle(content, lines, result)
            
            # Calculate validation score
            result.validation_score = self._calculate_score(result)
            
        except Exception as e:
            print(f"{Colors.FAIL}❌ Error reading file {file_path}: {str(e)}{Colors.ENDC}")
        
        return result
    
    def _check_tracker_import(self, content: str, lines: List[str], 
                             result: FileValidationResult) -> None:
        """Check if UIProgressTracker is properly imported when needed."""
        # Skip files that are the tracker itself or don't need tracking
        file_path = result.file_path.lower()
        if 'ui_progress_tracker' in file_path or 'streaming' in file_path:
            return
        
        # Check if file has analysis/processing logic that should use tracker
        has_analysis_logic = any([
            'def analyze' in content,
            'def process' in content,
            'def evaluate' in content,
            'def run_analysis' in content
        ])
        
        if not has_analysis_logic:
            return
        
        # Check for proper import
        has_tracker_import = any(
            import_line in content for import_line in REQUIRED_TRACKER_IMPORTS
        )
        
        if not has_tracker_import:
            # Find first analysis function line
            for line_num, line in enumerate(lines, start=1):
                if 'def analyze' in line or 'def process' in line or 'def evaluate' in line:
                    result.violations.append(ContractViolation(
                        line_number=line_num,
                        violation_type="missing_tracker_import",
                        severity="critical",
                        message="File has analysis logic but doesn't import UIProgressTracker",
                        code_snippet=line.strip(),
                        fix_suggestion="Add: from src.ui_progress_tracker import UIProgressTracker"
                    ))
                    break
    
    def _check_tracker_initialization(self, content: str, lines: List[str], 
                                     result: FileValidationResult) -> None:
        """Check that UIProgressTracker is initialized with required parameters."""
        # Look for UIProgressTracker instantiation
        tracker_pattern = r'UIProgressTracker\s*\('
        
        for line_num, line in enumerate(lines, start=1):
            if re.search(tracker_pattern, line):
                # Get context for initialization (next 15 lines)
                context_start = line_num - 1
                context_end = min(len(lines), line_num + 15)
                context = '\n'.join(lines[context_start:context_end])
                
                # Check for required parameters
                for param, description in REQUIRED_TRACKER_PARAMS.items():
                    if param not in context:
                        result.violations.append(ContractViolation(
                            line_number=line_num,
                            violation_type="missing_tracker_parameter",
                            severity="critical" if param == "session_id" else "warning",
                            message=f"UIProgressTracker initialization missing '{param}' parameter",
                            code_snippet=line.strip(),
                            fix_suggestion=f"Add {param}=... to UIProgressTracker() - {description}"
                        ))
                
                # Track that we found proper tracker usage
                result.approved_events.append({
                    "line": line_num,
                    "event_type": "tracker_init",
                    "code": line.strip()
                })
    
    def _check_session_id_usage(self, content: str, lines: List[str], 
                               result: FileValidationResult) -> None:
        """Check that session_id is properly used throughout the file."""
        # Skip the tracker implementation file itself
        if 'ui_progress_tracker' in result.file_path.lower():
            return
        
        # If file uses UIProgressTracker, check session_id is passed
        if 'UIProgressTracker' in content:
            # Look for tracker initialization without session_id in visible context
            tracker_pattern = r'UIProgressTracker\s*\([^)]{0,200}\)'
            
            for line_num, line in enumerate(lines, start=1):
                matches = re.finditer(tracker_pattern, line)
                for match in matches:
                    init_str = match.group(0)
                    
                    # Get extended context
                    context_start = max(0, line_num - 5)
                    context_end = min(len(lines), line_num + 10)
                    context = '\n'.join(lines[context_start:context_end])
                    
                    if 'session_id' not in context:
                        result.violations.append(ContractViolation(
                            line_number=line_num,
                            violation_type="missing_session_id",
                            severity="critical",
                            message="UIProgressTracker initialized without session_id - breaks session isolation!",
                            code_snippet=line.strip(),
                            fix_suggestion="Add session_id=session_id to UIProgressTracker initialization"
                        ))
    
    def _check_anti_patterns(self, content: str, lines: List[str], 
                           result: FileValidationResult) -> None:
        """Check for anti-patterns that indicate incorrect progress tracking."""
        # Skip streaming implementation files
        if 'streaming' in result.file_path.lower() or 'ui_progress_tracker' in result.file_path.lower():
            return
        
        for line_num, line in enumerate(lines, start=1):
            # Check for manual event creation (should use tracker instead)
            if re.search(ANTI_PATTERNS["manual_event_creation"], line):
                result.violations.append(ContractViolation(
                    line_number=line_num,
                    violation_type="manual_event_creation",
                    severity="critical",
                    message="Manually creating progress events - use UIProgressTracker instead!",
                    code_snippet=line.strip(),
                    fix_suggestion="Replace manual event creation with UIProgressTracker.update() or UIProgressTracker.complete()"
                ))
            
            # Check for direct SSE streaming (should use tracker callback)
            if re.search(ANTI_PATTERNS["direct_sse_streaming"], line):
                result.violations.append(ContractViolation(
                    line_number=line_num,
                    violation_type="direct_sse_manipulation",
                    severity="critical",
                    message="Directly manipulating SSE streams - use UIProgressTracker instead!",
                    code_snippet=line.strip(),
                    fix_suggestion="Use UIProgressTracker with progress_callback instead of format_sse() directly"
                ))
    
    def _check_tracker_lifecycle(self, content: str, lines: List[str], 
                                result: FileValidationResult) -> None:
        """Check that tracker lifecycle methods are called properly."""
        # If file creates a tracker, check lifecycle
        if 'UIProgressTracker(' not in content:
            return
        
        # Check for start() call
        if '.start()' not in content and 'tracker.start()' not in content:
            for line_num, line in enumerate(lines, start=1):
                if 'UIProgressTracker(' in line:
                    result.violations.append(ContractViolation(
                        line_number=line_num,
                        violation_type="missing_tracker_start",
                        severity="warning",
                        message="UIProgressTracker created but start() not called",
                        code_snippet=line.strip(),
                        fix_suggestion="Call tracker.start() after initialization to send analysis_start event"
                    ))
                    break
        
        # Check for complete() call
        if '.complete(' not in content and 'tracker.complete(' not in content:
            for line_num, line in enumerate(lines, start=1):
                if 'UIProgressTracker(' in line:
                    result.violations.append(ContractViolation(
                        line_number=line_num,
                        violation_type="missing_tracker_complete",
                        severity="warning",
                        message="UIProgressTracker created but complete() not called",
                        code_snippet=line.strip(),
                        fix_suggestion="Call tracker.complete(success=True/False) to send analysis_completion event"
                        ))
                    break
    
    def _check_unauthorized_emojis(self, content: str, lines: List[str], 
                                   result: FileValidationResult) -> None:
        """Check for emojis not in approved list."""
        # Extract all emojis from content
        emoji_pattern = re.compile(r'[\U0001F300-\U0001F9FF]|[\U00002600-\U000027BF]')
        
        for line_num, line in enumerate(lines, start=1):
            found_emojis = emoji_pattern.findall(line)
            for emoji in found_emojis:
                if emoji not in APPROVED_EMOJIS:
                    result.violations.append(ContractViolation(
                        line_number=line_num,
                        violation_type="unauthorized_emoji",
                        severity="warning",
                        message=f"Unauthorized emoji: {emoji}",
                        code_snippet=line.strip()[:100],
                        fix_suggestion=f"Use approved emojis: {', '.join(APPROVED_EMOJIS.keys())}"
                    ))
    
    def _calculate_score(self, result: FileValidationResult) -> float:
        """
        Calculate validation score (0-100).
        
        Scoring:
        - Start at 100
        - -20 per critical violation
        - -5 per warning
        - -1 per info violation
        """
        score = 100.0
        
        for violation in result.violations:
            if violation.severity == 'critical':
                score -= 20
            elif violation.severity == 'warning':
                score -= 5
            elif violation.severity == 'info':
                score -= 1
        
        return max(0.0, score)
    
    def print_summary(self) -> None:
        """Print validation summary."""
        print(f"\n{Colors.HEADER}{'=' * 80}{Colors.ENDC}")
        print(f"{Colors.HEADER}{Colors.BOLD}📊 VALIDATION SUMMARY{Colors.ENDC}")
        print(f"{Colors.HEADER}{'=' * 80}{Colors.ENDC}\n")
        
        # Count totals
        total_files = len(self.results)
        files_with_violations = sum(1 for r in self.results.values() if r.violations)
        total_violations = sum(len(r.violations) for r in self.results.values())
        total_critical = sum(
            sum(1 for v in r.violations if v.severity == 'critical')
            for r in self.results.values()
        )
        total_warnings = sum(
            sum(1 for v in r.violations if v.severity == 'warning')
            for r in self.results.values()
        )
        
        if total_critical > 0:
            print(f"{Colors.FAIL}{Colors.BOLD}❌ CRITICAL CONTRACT VIOLATIONS FOUND{Colors.ENDC}\n")
        elif total_warnings > 0:
            print(f"{Colors.WARNING}{Colors.BOLD}⚠️  WARNINGS FOUND{Colors.ENDC}\n")
        else:
            print(f"{Colors.OKGREEN}{Colors.BOLD}✅ ALL FILES PASS CONTRACT VALIDATION{Colors.ENDC}\n")
        
        print(f"Files Checked: {total_files}")
        print(f"  {Colors.OKGREEN}✓ Compliant: {total_files - files_with_violations}{Colors.ENDC}")
        print(f"  {Colors.FAIL}✗ With Violations: {files_with_violations}{Colors.ENDC}\n")
        
        print(f"Violations Found: {total_violations}")
        print(f"  {Colors.FAIL}Critical: {total_critical}{Colors.ENDC}")
        print(f"  {Colors.WARNING}Warnings: {total_warnings}{Colors.ENDC}\n")
        
        # Print individual file scores
        print(f"{Colors.BOLD}Individual File Scores:{Colors.ENDC}")
        for file_path, result in sorted(self.results.items(), key=lambda x: x[1].validation_score):
            score = result.validation_score
            if score == 100:
                color = Colors.OKGREEN
                icon = "✅"
            elif score >= 80:
                color = Colors.WARNING
                icon = "⚠️ "
            else:
                color = Colors.FAIL
                icon = "❌"
            
            # Shorten file path for display
            short_path = file_path.replace('\\', '/').split('/')[-1]
            print(f"  {color}{icon} {short_path:50s} {score:6.1f}/100{Colors.ENDC}")
        
        # Print detailed violations
        if total_violations > 0:
            print(f"\n{Colors.BOLD}{'='*80}")
            print(f"📋 DETAILED FIX INSTRUCTIONS")
            print(f"{'='*80}{Colors.ENDC}")
            
            violation_num = 1
            for file_path, result in self.results.items():
                if not result.violations:
                    continue
                
                for violation in result.violations:
                    if violation.severity == 'critical':
                        color = Colors.FAIL
                        severity_label = "🔴 CRITICAL"
                    elif violation.severity == 'warning':
                        color = Colors.WARNING
                        severity_label = "🟡 WARNING"
                    else:
                        color = Colors.OKBLUE
                        severity_label = "🔵 INFO"
                    
                    print(f"\n{color}{'─'*80}")
                    print(f"Issue #{violation_num}: {severity_label}")
                    print(f"{'─'*80}{Colors.ENDC}")
                    
                    print(f"\n{Colors.BOLD}📍 Location:{Colors.ENDC}")
                    print(f"   File: {file_path}")
                    print(f"   Line: {violation.line_number}")
                    
                    print(f"\n{Colors.BOLD}❌ Problem Found:{Colors.ENDC}")
                    print(f"   {violation.violation_type.replace('_', ' ').title()}")
                    print(f"\n   Current code at line {violation.line_number}:")
                    print(f"   {color}{violation.code_snippet}{Colors.ENDC}")
                    
                    print(f"\n{Colors.BOLD}⚠️  Why This Breaks The UI:{Colors.ENDC}")
                    print(f"   {violation.message}")
                    
                    if violation.severity == 'critical':
                        print(f"\n{Colors.BOLD}💥 Impact:{Colors.ENDC}")
                        print(f"   {Colors.FAIL}This BLOCKS deployment - frontend won't handle this correctly{Colors.ENDC}")
                    
                    print(f"\n{Colors.BOLD}🔧 Step-by-Step Fix:{Colors.ENDC}")
                    print(f"   1. Open: {file_path}")
                    print(f"   2. Navigate to: Line {violation.line_number}")
                    print(f"   3. {violation.fix_suggestion}")
                    
                    # Add specific before/after examples based on violation type
                    if violation.violation_type == 'missing_tracker_import':
                        print(f"\n{Colors.BOLD}✅ Before → After Example:{Colors.ENDC}")
                        print(f"   {Colors.FAIL}❌ No UIProgressTracker import{Colors.ENDC}")
                        print(f"   {Colors.OKGREEN}✅ from src.ui_progress_tracker import UIProgressTracker{Colors.ENDC}")
                    
                    elif violation.violation_type == 'missing_tracker_parameter':
                        print(f"\n{Colors.BOLD}✅ Before → After Example:{Colors.ENDC}")
                        print(f"   {Colors.FAIL}❌ tracker = UIProgressTracker(analysis_name=\"Test\"){Colors.ENDC}")
                        print(f"   {Colors.OKGREEN}✅ tracker = UIProgressTracker(analysis_name=\"Test\", session_id=session_id, progress_callback=callback, total_items=100){Colors.ENDC}")
                    
                    elif violation.violation_type == 'missing_session_id':
                        print(f"\n{Colors.BOLD}✅ Before → After Example:{Colors.ENDC}")
                        print(f"   {Colors.FAIL}❌ tracker = UIProgressTracker(analysis_name=\"Test\"){Colors.ENDC}")
                        print(f"   {Colors.OKGREEN}✅ tracker = UIProgressTracker(analysis_name=\"Test\", session_id=session_id){Colors.ENDC}")
                    
                    elif violation.violation_type == 'manual_event_creation':
                        print(f"\n{Colors.BOLD}✅ Before → After Example:{Colors.ENDC}")
                        print(f"   {Colors.FAIL}❌ callback({{\"type\": \"progress_update\", \"percentage\": 50}}){Colors.ENDC}")
                        print(f"   {Colors.OKGREEN}✅ tracker.update(50)  # UIProgressTracker handles event creation{Colors.ENDC}")
                    
                    elif violation.violation_type == 'direct_sse_manipulation':
                        print(f"\n{Colors.BOLD}✅ Before → After Example:{Colors.ENDC}")
                        print(f"   {Colors.FAIL}❌ yield format_sse(json.dumps(data), event=\"progress_update\"){Colors.ENDC}")
                        print(f"   {Colors.OKGREEN}✅ Use UIProgressTracker with progress_callback instead{Colors.ENDC}")
                    
                    elif violation.violation_type in ['missing_tracker_start', 'missing_tracker_complete']:
                        print(f"\n{Colors.BOLD}✅ Before → After Example:{Colors.ENDC}")
                        print(f"   {Colors.FAIL}❌ tracker = UIProgressTracker(...) # No lifecycle calls{Colors.ENDC}")
                        print(f"   {Colors.OKGREEN}✅ tracker = UIProgressTracker(...){Colors.ENDC}")
                        print(f"   {Colors.OKGREEN}✅ tracker.start()  # Send analysis_start{Colors.ENDC}")
                        print(f"   {Colors.OKGREEN}✅ tracker.update(...)  # Send progress{Colors.ENDC}")
                        print(f"   {Colors.OKGREEN}✅ tracker.complete(success=True)  # Send analysis_completion{Colors.ENDC}")
                    
                    elif violation.violation_type == 'unauthorized_emoji':
                        print(f"\n{Colors.BOLD}✅ Approved Emojis:{Colors.ENDC}")
                        for emoji, meaning in APPROVED_EMOJIS.items():
                            print(f"     {emoji} - {meaning}")
                    
                    print(f"\n{Colors.BOLD}✓ Verification:{Colors.ENDC}")
                    print(f"   Run: python uiFrontendContractChecker.py")
                    print(f"   Expected: Issue #{violation_num} should disappear")
                    
                    violation_num += 1
            
            print(f"\n{color}{'='*80}{Colors.ENDC}")
        else:
            print(f"\n{Colors.OKGREEN}✅ No violations found - all backend code follows frontend contract!{Colors.ENDC}")
        
        # Print recommendations
        print(f"\n{Colors.BOLD}Recommendations:{Colors.ENDC}")
        if total_critical > 0:
            print(f"  {Colors.FAIL}❌ DEPLOYMENT BLOCKED - Fix critical violations before deploying{Colors.ENDC}")
            print(f"     These violations will break the UI tracker!")
        elif total_warnings > 0:
            print(f"  {Colors.WARNING}⚠️  Review warnings - may cause UI inconsistencies{Colors.ENDC}")
        else:
            print(f"  {Colors.OKGREEN}✅ All backend code follows frontend contract - safe to deploy{Colors.ENDC}")
        
        print(f"\n{Colors.HEADER}{'=' * 80}{Colors.ENDC}\n")
    
    def generate_report(self, output_file: Optional[str] = None) -> str:
        """
        Generate detailed text report.
        
        Args:
            output_file: Optional file path to save report
            
        Returns:
            Report text
        """
        report_lines = []
        report_lines.append("=" * 80)
        report_lines.append("UI FRONTEND CONTRACT VALIDATION REPORT")
        report_lines.append("=" * 80)
        report_lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        report_lines.append("")
        
        # Summary
        total_files = len(self.results)
        files_with_violations = sum(1 for r in self.results.values() if r.violations)
        total_violations = sum(len(r.violations) for r in self.results.values())
        total_critical = sum(
            sum(1 for v in r.violations if v.severity == 'critical')
            for r in self.results.values()
        )
        
        report_lines.append("SUMMARY")
        report_lines.append("-" * 80)
        report_lines.append(f"Files Checked: {total_files}")
        report_lines.append(f"Files with Violations: {files_with_violations}")
        report_lines.append(f"Total Violations: {total_violations}")
        report_lines.append(f"  Critical: {total_critical}")
        report_lines.append("")
        
        # Detailed results
        for file_path, result in self.results.items():
            report_lines.append("")
            report_lines.append("=" * 80)
            report_lines.append(f"File: {file_path}")
            report_lines.append(f"Score: {result.validation_score}/100")
            report_lines.append("=" * 80)
            
            if not result.violations:
                report_lines.append("✅ No contract violations found")
                continue
            
            report_lines.append(f"Violations: {len(result.violations)}")
            report_lines.append("")
            
            for violation in result.violations:
                report_lines.append(f"Line {violation.line_number}: [{violation.severity.upper()}] {violation.violation_type}")
                report_lines.append(f"  Message: {violation.message}")
                report_lines.append(f"  Code: {violation.code_snippet}")
                report_lines.append(f"  Fix: {violation.fix_suggestion}")
                report_lines.append("")
        
        report = '\n'.join(report_lines)
        
        if output_file:
            try:
                with open(output_file, 'w', encoding='utf-8') as f:
                    f.write(report)
                print(f"{Colors.OKGREEN}✅ Report saved to: {output_file}{Colors.ENDC}")
            except Exception as e:
                print(f"{Colors.FAIL}❌ Error saving report: {str(e)}{Colors.ENDC}")
        
        return report


def main():
    """Main entry point for the contract checker."""
    # Set UTF-8 encoding for Windows console
    if sys.platform == 'win32':
        try:
            import codecs
            sys.stdout = codecs.getwriter('utf-8')(sys.stdout.buffer, 'strict')
            sys.stderr = codecs.getwriter('utf-8')(sys.stderr.buffer, 'strict')
        except Exception:
            pass  # If encoding setup fails, continue anyway
    
    parser = argparse.ArgumentParser(
        description='Validate backend-frontend SSE contract compliance',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python uiFrontendContractChecker.py                    # Check all backend files
  python uiFrontendContractChecker.py --verbose          # Show detailed analysis
  python uiFrontendContractChecker.py --report           # Generate text report
  python uiFrontendContractChecker.py --output report.txt # Save report to file
        """
    )
    
    parser.add_argument(
        '--path',
        type=str,
        default=None,
        help='Base path of the project (default: current directory)'
    )
    
    parser.add_argument(
        '--verbose', '-v',
        action='store_true',
        help='Enable verbose output with detailed analysis'
    )
    
    parser.add_argument(
        '--report', '-r',
        action='store_true',
        help='Generate detailed text report'
    )
    
    parser.add_argument(
        '--output', '-o',
        type=str,
        default=None,
        help='Save report to specified file'
    )
    
    args = parser.parse_args()
    
    # Create checker and run validation
    checker = FrontendContractChecker(base_path=args.path, verbose=args.verbose)
    results = checker.check_all_backend_files()
    
    if not results:
        print(f"{Colors.FAIL}❌ Validation failed - no results generated{Colors.ENDC}")
        return 1
    
    # Print summary
    checker.print_summary()
    
    # Generate report if requested
    if args.report or args.output:
        checker.generate_report(output_file=args.output)
    
    # Exit with appropriate code
    total_critical = sum(
        sum(1 for v in r.violations if v.severity == 'critical')
        for r in results.values()
    )
    
    if total_critical > 0:
        return 1  # Fail build/deployment
    else:
        return 0  # Success


if __name__ == '__main__':
    sys.exit(main())
